version: '3.7'

services:
  spark:
    image: jupyter/all-spark-notebook:latest
    ports:
      - "8888:8888"
    volumes:
      - ./:/app
    environment:
      - PYSPARK_PYTHON=python3
    working_dir: /app
